version: '3'
services:
  db:
    image: postgres:latest 
    ports:
      - "5435:5435"  
    environment:
      POSTGRES_DB: usuarios 
      POSTGRES_USER: admin   
      POSTGRES_PASSWORD: admin 
      


  client:
    build: ./Client
    ports:
      - "4200:4200" 
    

  server:
    build: ./Server
    ports:
      - "5000:5000"  
    depends_on:
      - db  
    
