version: '3'
services:
  db:
    image: mysql:latest
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: usuario
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  client:
    build: ./Client
    ports:
      - "4200:4200" 
    

  server:
    build: ./Server
    ports:
      - "5000:5000"  
    depends_on:
      - db  
    
volumes:
  db_data:

